services:
  test-echo-sql:
    container_name: test-echo-sql
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-test}
    ports:
      - "127.0.0.1:5432:5432"

